In [31]:
import numpy as np 
class NeuralNetworks(object):
    def __init__(self) :
        #Make Paramters
        self.inputsize=2
        self.outputsize=1
        self.hiddensize=3
        #Make Weights Matrix for my data
        self.w1=np.random.randn(self.inputsize,self.hiddensize)
        print('The Matrix Of Weights 1 Is  \n',self.w1)
        print('=='*20)
        self.w2=np.random.randn(self.hiddensize,self.outputsize)
        print('The Matrix Of Weights 2 Is \n',self.w2)
        print('=='*20)
    #=====================================================================================================================
    def forward_propagation(self,x):
        self.z1=np.dot(x,self.w1) # Product x_input  * weights_one
        self.z2=self.sigmoid_func(self.z1)#Send The Matrix Of Z To Sigmoid Function To Return The Activation Value(a1)
        self.z3=np.dot(self.z2,self.w2)#Product activation_value(a1) * matrix Of Weights 
        a = self.sigmoid_func(self.z3)#Final Activation Value (The Final Expected Value )
        return a
    #=====================================================================================================================
    def sigmoid_func(self,num1):return  1.0 / (1.0 + np.exp(-num1))
    #=====================================================================================================================
    def dervative_sigmoid(self,num2): return num2  * (1 - num2) 
    #====================================================================================================================
    def backward_prop(self,x,y,a):
        self.a_error= y - a  #Error Output 
        self.a_delta= self.a_error * self.dervative_sigmoid(a)
        self.z2_error=self.a_delta.dot(self.w2.T)
        self.z2_delta=self.z2_error * self.dervative_sigmoid(self.z2)
        self.w1+=x.T.dot(self.z2_delta)
        self.w2+=self.z2.T.dot(self.a_delta)
    #======================================================================================================================
    def train_data(self,x,y):
        a = self.forward_propagation(x)
        self.backward_prop(x,y,a)
    #========================================================================================================================
    def save_weights(self):
        np.savetxt("w1.txt" , self.w1, fmt="%s")
        np.savetxt("w2.txt" , self.w1, fmt="%s")
    #========================================================================================================================
    def predict(self):
        print('Predicted Data Based On Trained Weights  : ')
        print('Input Scaling Data Is  \n' +str(predicted_score) )
        print('Output : \n ' + str(self.forward_propagation(predicted_score)))
#====================================================================================================================================================================================
#Enter Your Data 
#Data = (Hours Of Studying, Hours Of Sleeping),Y=Score Of Test , Predicted_Data For (4 Hours Of Studying , 8 Hours Of Sleeping)
x_data=np.array(([2,9],[1,5,],[3,6,]),dtype=float)
y_data=np.array(([92],[86],[89]),dtype=float)
predicted_score=np.array(([4,8]),dtype=float)
#print("the x data before scaling is \n",x_data)
#make scaling for data 
#print('***'*20)
x_data=x_data / np.amax (x_data,axis=0)#make scaling instead of column
#print('the x_data after make scaling is \n',x_data)
#print('***'*20)
#print('predicted score before making sacle is \n',predicted_score)
#and making scale for predicted
predicted_score=predicted_score / np.amax(predicted_score,axis=0)
#print('***'*20)
#print('the predicted score after make scaling is \n',predicted_score)
#print('***'*20)
#divided y_data over 100 
y_data = y_data /100
#print('The Matrix Of Y_data Is \n',y_data)
#print('****'*50)
##################################################################################################################################################################################
#Caling Neural Networks 
NN=NeuralNetworks()
for i in range (10000):
    print('#The Number Of Iteration ' + str(i) + " is  ==> " )
    #print('Input The Sacling Data : \n ' + str(x_data))
    #print('\n')
    #print('The Actual Data Is : \n '     + str (y_data))
    #print('\n')
    #print('#Predicted Output Is : \n '    + str(NN.forward_propagation(x_data)))
    #print('\n')
    print('#Loss Data Is ==>  ' + str(np.mean(np.square(y_data - NN.forward_propagation(x_data)))))
    print('=='*30)
    NN.train_data(x_data,y_data)
#===================================================================================================================================================================================
NN.save_weights()
NN.predict()

The Matrix Of Weights 1 Is  
 [[-1.07616982  0.55965093  2.16370932]
 [ 1.54680848  1.3705224   0.15763167]]
The Matrix Of Weights 2 Is 
 [[ 1.35981816]
 [-1.54926292]
 [-2.51477057]]
#The Number Of Iteration 0 is  ==> 
#Loss Data Is ==>  0.6528230426594698
#The Number Of Iteration 1 is  ==> 
#Loss Data Is ==>  0.606793527340432
#The Number Of Iteration 2 is  ==> 
#Loss Data Is ==>  0.5331320251407239
#The Number Of Iteration 3 is  ==> 
#Loss Data Is ==>  0.4160173775368358
#The Number Of Iteration 4 is  ==> 
#Loss Data Is ==>  0.2573512892224045
#The Number Of Iteration 5 is  ==> 
#Loss Data Is ==>  0.12035111454265497
#The Number Of Iteration 6 is  ==> 
#Loss Data Is ==>  0.05489323118633851
#The Number Of Iteration 7 is  ==> 
#Loss Data Is ==>  0.029473104337800607
#The Number Of Iteration 8 is  ==> 
#Loss Data Is ==>  0.01809369932346422
#The Number Of Iteration 9 is  ==> 
#Loss Data Is ==>  0.012133265963049996
#The Number Of Iteration 10 is  ==> 
#Loss Data Is ==>  0.008640969926